### ISSUE TITLE
option to specify bounds on plotKDE

### ISSUE THREAD

**Issue by mpilosov** [JuliaRobotics/KernelDensityEstimate.jl#15]
Hi, I was wondering if the rmin/rmax properties can be reinstated into the plotting options? Or if there's a workaround?
I'm trying to look at a 1D density on [0,1] and no matter what I try, the x-axis defaults to [0,15] (odd enough, considering my data was in [0,1] to begin with), so I cannot actually tell what is going on in my region of interest.

Otherwise, love the plotting functionality.

**Comment by dehann** [comment]
Hi @mpilosov , sorry response has been slow. There is some functionality for defining the plotting dimension. I used to be rmin/rmax, but I was going to deprecate this. I switched to using `axis`. Although only works for defining larger axis at this point. For example you should see this work:
```julia
axis = zeros(1,2)
axis[1,1] = -10
plotKDE(kde!(randn(1,100)), axis=axis)
```
