### ISSUE TITLE
Function Usage

### ISSUE THREAD

**Issue by wadehenning** [JuliaRobotics/KernelDensityEstimate.jl#2]
Hi @dehann.  
I am mostly interested in finding the likelihood that a given random variable is a member of a sample (for both scalar valued and multivariate random variables).  This seems to be what you are plotting in your examples, but I can't unpack how you arrive at those values.  Using the 'calcStatsHandle' perhaps?

I am also interested in your product approximation.  How do you interpret this product?  It looks like the average of the densities...

Thank You,
Wade

**Comment by wadehenning** [comment]
@dehann I wanted to send a reminder on this in case you missed it.  Thanks.

**Comment by dehann** [comment]
Hi @wadehenning, yeah sorry I missed the first message.

To evaluate you can use [this as example](https://github.com/dehann/KernelDensityEstimate.jl/blob/master/src/KDEPlotting01.jl#L15). You call the evaluateDualTree function with a density and bins you are interested in. Also:
```
julia> evaluateDualTree(kde!(randn(100)),[-2.0;-1;0;1;2])
5-element Array{Float64,1}:
 0.052723 
 0.224875 
 0.368687 
 0.247842 
 0.0869894
```

The product is acquired through multiscale Gibbs sampling. Best is to see publications from the original work: 
```
Sudderth, Erik B.; Ihler, Alexander, et al. "Nonparametric belief propagation." Communications of the ACM 53.10 (2010): 95-103.
```

There are two PhD thesis related to this work by the same author. It's probably best to consult their description for a more accurate description.

Have you found a solution for plotting in Windows by any chance? What do you normally use -- I'm interested in separating out the plotting and allowing the user to pick the plotting library of choice. Hopefully that boils down to a function and quick wrapper for each library...

**Comment by dehann** [comment]
multidimensional evaluations work fine too.

**Comment by wadehenning** [comment]
Thanks for the excellent example, @dehann; I am really looking forward to exploring this package.  

I am currently having good luck with PyPlot.jl and plan on moving to the Plots.jl framework at some point.
