### ISSUE TITLE
How to evaluate the log probability of fitted model?

### ISSUE THREAD

**Issue by juliohm** [JuliaRobotics/KernelDensityEstimate.jl#27]
I am trying to guess by reading the source code, but I am not 100% sure. Could you please clarify two basic questions. Assume I have fitted a 4D KDE.

1. How to evaluate the log-probability at a new point?
2. How to sample from the KDE?

I think for the latter, there is `sample(kdeobj, npts)`, correct? Could you please comment on the output? I remember it returning a tuple? What is the meaning of the second entry?

For the former, I found a set of `eval*` methods with very complicated arguments, I appreciate if you can clarify those.

Thanks,

**Comment by dehann** [comment]
Regarding sampling, you can just do
```julia
p = kde!(randn(100))
pts = randn(p, 1000)
```

**Comment by juliohm** [comment]
Thank you @dehann , I will keep it in mind next time I need KDE in my work, this time I had to rely on the Python's sklearn implementation due to an urgent deadline.
