### ISSUE TITLE
Leave-one-out estimation of the bandwidth

### ISSUE THREAD

**Issue by andreyzhitnikov** [JuliaRobotics/KernelDensityEstimate.jl#66]
Hi, I'm wondering how hard is to add a leave-one-out cross validation estimator for optimal bandwidth?

**Comment by dehann** [comment]
Hi @andreyzhitnikov , if I understand you correctly this package already is using a LOOCV:
https://github.com/JuliaRobotics/KernelDensityEstimate.jl/blob/caab2b12a108ee1a41af9608bd602baa429e1ada/src/CrossValidation.jl#L15-L30

The name just might not be so obvious.  Leave one out cross validation (LOOCV) was the only bandwidth selection technique that performed okay with multimodal beliefs (my interest and reason for porting the package here).  Other bandwidth techniques tend to assume unimodal and would wildly oversmooth multimodal beliefs.

**Comment by andreyzhitnikov** [comment]
Thanks!
