### ISSUE TITLE
what does the function kde! modify?

### ISSUE THREAD

**Issue by urlicht** [JuliaRobotics/KernelDensityEstimate.jl#95]
By convention in Julia, a function that ends with `!` modifies some of its input arguments.

It seems like `kde!` can be called with only the data for the estimation. Does the function modify the input data? If so, it'd be great to clarify on the usage case and give an option that doesn't modify the input data

**Comment by dehann** [comment]
Hi, yes `!` is used in a sort of inverse way to indicate that the first argument (the data points) are used directly in the computation and not copied.  The `kde!` function builds a rather intricate tree structure of the data.  The use of `!` here rather indicates that if the user changes the input data vector, then the data structure `kde!` built would no longer be valid.

If this is an issue, the recommended use would be:
```julia
P  = kde!(deepcopy(data))
```
